version: '3.8'
services:
  home-navigation:
    build: ./navigation-home-frontend
    ports:
      - "3999:3999"

  carfrontend:
    build: ./carfrontend
    ports:
      - "4000:4000"

  rentalfrontend:
    build: ./rentalfrontend
    ports:
      - "4001:4001"

  userfrontend:
    build: ./userfrontend  
    ports:
      - "4002:4002"
