version: '3.8'
services:
  home-navigation:
    image: peter752/navigation-home-frontend
    ports:
      - "3999:3999"

  carfrontend:
    image: peter752/carfrontend
    ports:
      - "4000:4000"

  rentalfrontend:
    image: peter752/rentalfrontend
    ports:
      - "4001:4001"

  userfrontend:
    image: peter752/userfrontend 
    ports:
      - "4002:4002"
